In [49]:
import torch
import numpy as np

In [47]:
pretty_midi.instrument_name_to_program('Pad 1 (new age)')

88

In [19]:
metrics = {k:torch.randint(high=10, size=(1,)).cuda() for k in range(10)}

In [22]:
values = list(metrics.values())

In [24]:
np.log(values)

array([tensor([1.9459], device='cuda:0'),
       tensor([1.9459], device='cuda:0'),
       tensor([1.0986], device='cuda:0'),
       tensor([1.9459], device='cuda:0'),
       tensor([2.1972], device='cuda:0'),
       tensor([1.0986], device='cuda:0'),
       tensor([0.6931], device='cuda:0'), tensor([-inf], device='cuda:0'),
       tensor([-inf], device='cuda:0'), tensor([1.0986], device='cuda:0')],
      dtype=object)

In [10]:
x = torch.randn(4,1001,229).cuda()

In [11]:
np.log(x)

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [7]:
from MIDI_program_map import (MIDI_PROGRAM_NUM,
                                      MIDIProgramName2class_idx,
                                      class_idx2MIDIProgramName,
                                      MIDI_Class_NUM,
                                      MIDIClassName2class_idx,
                                      class_idx2MIDIClass,
                                      W_MIDI_Class_NUM,
                                      W_MIDIClassName2class_idx,
                                      W_class_idx2MIDIClass,
                                      )

FileNotFoundError: [Errno 2] No such file or directory: './End2End/MIDI_program_map.tsv'

In [2]:
import pickle
import csv
with open('./MIDI_program_map.tsv') as csv_file:
    csv_reader = csv.reader(csv_file, delimiter='\t')
    line_count = 0
    idx2class_name = {}
    idx2instrument_name = {}
    idx2instrument_class = {}
    for row in csv_reader:
        idx2class_name[int(row[0])] = row[1]
        idx2instrument_name[int(row[0])] = row[2]
        idx2instrument_class[int(row[0])] = row[3]      
        
        
slakh_instrument = pickle.load(open('./slakh_instruments.pkl', 'rb')) # This is the midi channel for slakh

MIDIProgramName2class_idx = {}
class_idx2MIDIProgramName = {}

MIDIClassName2class_idx = {}
class_idx2MIDIClass = {}
for idx,i in enumerate(slakh_instrument):
    MIDIProgramName2class_idx[idx2instrument_name[i]] = idx
    class_idx2MIDIProgramName[idx] = idx2instrument_name[i]
    
    MIDIClassName2class_idx[idx2instrument_class[i]] = idx
    class_idx2MIDIClass[idx] = idx2instrument_class[i]    

In [4]:
class_idx2MIDIClass

{0: 'Piano',
 1: 'Piano',
 2: 'Piano',
 3: 'Piano',
 4: 'Electric Piano',
 5: 'Electric Piano',
 6: 'Harpsichord',
 7: 'Clavinet',
 8: 'Chromatic Percussion',
 9: 'Chromatic Percussion',
 10: 'Chromatic Percussion',
 11: 'Chromatic Percussion',
 12: 'Chromatic Percussion',
 13: 'Chromatic Percussion',
 14: 'Chromatic Percussion',
 15: 'Chromatic Percussion',
 16: 'Organ',
 17: 'Organ',
 18: 'Organ',
 19: 'Organ',
 20: 'Organ',
 21: 'Accordion',
 22: 'Harmonica',
 23: 'Accordion',
 24: 'Guitar',
 25: 'Guitar',
 26: 'Guitar',
 27: 'Guitar',
 28: 'Guitar',
 29: 'Guitar',
 30: 'Guitar',
 31: 'Guitar',
 32: 'Bass',
 33: 'Bass',
 34: 'Bass',
 35: 'Bass',
 36: 'Bass',
 37: 'Bass',
 38: 'Violin',
 39: 'Viola',
 40: 'Cello',
 41: 'Contrabass',
 42: 'Strings',
 43: 'Strings',
 44: 'Harp',
 45: 'Timpani',
 46: 'Strings',
 47: 'Strings',
 48: 'Strings',
 49: 'Strings',
 50: 'Voice',
 51: 'Voice',
 52: 'Voice',
 53: 'Trumpet',
 54: 'Trombone',
 55: 'Tuba',
 56: 'Trumpet',
 57: 'Horn',
 58: 'Brass',

In [3]:
MIDIClassName2class_idx

{'Piano': 3,
 'Electric Piano': 5,
 'Harpsichord': 6,
 'Clavinet': 7,
 'Chromatic Percussion': 15,
 'Organ': 20,
 'Accordion': 23,
 'Harmonica': 22,
 'Guitar': 31,
 'Bass': 37,
 'Violin': 38,
 'Viola': 39,
 'Cello': 40,
 'Contrabass': 41,
 'Strings': 49,
 'Harp': 44,
 'Timpani': 45,
 'Voice': 52,
 'Trumpet': 56,
 'Trombone': 54,
 'Tuba': 55,
 'Horn': 64,
 'Brass': 58,
 'Saxophone': 62,
 'Oboe': 63,
 'Bassoon': 65,
 'Clarinet': 66,
 'Piccolo': 67,
 'Flute': 68,
 'Recorder': 69,
 'Pipe': 74,
 'Synth Lead': 82,
 'Synth Pad': 90}

In [39]:
for idx,i in enumerate(slakh_instrument):
    MIDIClassName2class_idx[idx2instrument_class[i]] = idx    

In [40]:
MIDIClassName2class_idx

{'Piano': 3,
 'Synth Lead': 82,
 'Strings': 49,
 'Contrabass': 41,
 'Viola': 39,
 'Cello': 40,
 'Trombone': 54,
 'Bass': 37,
 'Guitar': 31,
 'Harp': 44,
 'Electric Piano': 5,
 'Harmonica': 22,
 'Ethnic': 12,
 'Sound Effects': 13,
 'Recorder': 69,
 'Pipe': 74,
 'Percussive': 16,
 'Harpsichord': 6,
 'Trumpet': 56,
 'Accordion': 23,
 'Flute': 68,
 'Synth Pad': 90,
 'Violin': 38,
 'Piccolo': 67,
 'Tuba': 55,
 'Bassoon': 65,
 'Oboe': 63,
 'Synth Effects': 27,
 'Voice': 52,
 'Timpani': 45,
 'Chromatic Percussion': 15,
 'Clarinet': 66,
 'Horn': 64,
 'Brass': 58,
 'Saxophone': 62,
 'Clavinet': 7,
 'Organ': 20}

In [22]:
for i in class_idx2MIDIClass:
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90


In [21]:
MIDIClassName2class_idx

{'Piano': 3,
 'Electric Piano': 5,
 'Harpsichord': 6,
 'Clavinet': 7,
 'Chromatic Percussion': 15,
 'Organ': 20,
 'Accordion': 23,
 'Harmonica': 22,
 'Guitar': 31,
 'Bass': 37,
 'Violin': 38,
 'Viola': 39,
 'Cello': 40,
 'Contrabass': 41,
 'Strings': 49,
 'Harp': 44,
 'Timpani': 45,
 'Voice': 52,
 'Trumpet': 56,
 'Trombone': 54,
 'Tuba': 55,
 'Horn': 64,
 'Brass': 58,
 'Saxophone': 62,
 'Oboe': 63,
 'Bassoon': 65,
 'Clarinet': 66,
 'Piccolo': 67,
 'Flute': 68,
 'Recorder': 69,
 'Pipe': 74,
 'Synth Lead': 82,
 'Synth Pad': 90}

In [33]:
unique_instrument_class = set()
for i in idx2instrument_class.items():
    unique_instrument_class.update([i[1]])

In [34]:
unique_instrument_class

{'Accordion',
 'Bass',
 'Bassoon',
 'Brass',
 'Cello',
 'Chromatic Percussion',
 'Clarinet',
 'Clavinet',
 'Contrabass',
 'Electric Piano',
 'Ethnic',
 'Flute',
 'Guitar',
 'Harmonica',
 'Harp',
 'Harpsichord',
 'Horn',
 'Oboe',
 'Organ',
 'Percussive',
 'Piano',
 'Piccolo',
 'Pipe',
 'Recorder',
 'Saxophone',
 'Sound Effects',
 'Strings',
 'Synth Effects',
 'Synth Lead',
 'Synth Pad',
 'Timpani',
 'Trombone',
 'Trumpet',
 'Tuba',
 'Viola',
 'Violin',
 'Voice'}